14-My_Library/library_project/app_catalog/urls.py
from django.urls import path  # , include, re_path
from app_catalog import views

app_name = 'app_catalog'

urlpatterns = [
    # ex: catalog/
    path('', views.IndexView.as_view(), name='index'),
    path('book/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    # re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),  # noqa
    path('author/', views.AutorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),  # noqa
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name='borrowed-books'),  # noqa
    path('borrowed/', views.AllBorrowedBooksByUserListView.as_view(), name='borrowed-all'),  # noqa
    path('book/<uuid:pk>/renew/', views.RenewBookLibrarianView.as_view(), name='renew-book-librarian'),  # noqa
    # authors path
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),  # noqa
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),  # noqa
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),  # noqa
    # books path
    path('book/create/', views.BookCreate.as_view(), name='book-create'),  # noqa
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),  # noqa
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),  # noqa
]

14-My_Library/library_project/app_core/urls.py
"""
urls for the health check of the application
"""
from django.urls import path
from . import views

app_name = 'app_core'

urlpatterns = [
    # ex: health/
    path('health-check/', views.health_check, name='health-check'),
]

14-My_Library/library_project/library_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('health/', include('app_core.urls')),
    path('catalog/', include('app_catalog.urls')),
    # redirecting - root url to catalog
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    # adds django site authentication urls
    # accounts/ login/ [name='login']
    # accounts/ logout/ [name='logout']
    # accounts/ password_change/ [name='password_change']
    # accounts/ password_change/done/ [name='password_change_done']
    # accounts/ password_reset/ [name='password_reset']
    # accounts/ password_reset/done/ [name='password_reset_done']
    # accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/ reset/done/ [name='password_reset_complete']
    path('accounts/', include('django.contrib.auth.urls')),
]

# for serving files in development - only!!
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

14-My_Library/library_project/templates/library/includes/footer.html
<!-- Footer-->
<footer class="bg-dark">
    <div class="py-4 align-middle">
        <p class="m-0 text-center text-white">
            Copyright &copy; My-Library {{ current_year }}
        </p>
    </div>
</footer>

14-My_Library/library_project/templates/library/includes/pagination.html
{% if is_paginated %}
    <nav aria-label="All Books Page navigation ">
        <ul class="pagination">
            <li class="page-item">
                <a 
                    class="page-link {% if not page_obj.has_previous %}disabled{% endif %}" 
                    href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% else %}1{% endif %}" 
                    aria-label="Previous"
                >
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="?page=1">first</a></li>

            <li class="page-item current-page">
                <a class="page-link" href="?page={{ page_obj.number }}">
                    {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
                </a>
            </li>

            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
            <li class="page-item">
                <a 
                    class="page-link {% if not page_obj.has_next %}disabled{% endif %}" 
                    href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% else %}{{ page_obj.paginator.num_pages }}{% endif %}" 
                    aria-label="Next"
                >
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endif %}

{% comment %} {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %} {% endcomment %}


{% comment %} {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %} {% endcomment %}

14-My_Library/library_project/templates/library/includes/sidebar.html
<!-- Navigation-->
<ul class="sidebar-nav">
    <li><a href="{% url 'app_catalog:index' %}">Home</a></li>
    <li><a href="{% url 'app_catalog:books' %}">All books</a></li>
    <li><a href="{% url 'app_catalog:authors' %}">All authors</a></li>
    <br>
    {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
        <li><a href="{% url 'app_catalog:borrowed-books' %}">My Books</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
    {% endif %}
    {% if perms.app_catalog.can_view_staff %}
        <hr>
        <li>Staff</li>
        <li><a href="{% url 'app_catalog:borrowed-all' %}">All Borrowed</a></li>
    {% endif %}
</ul>