13-FundProjects_Django/FunctionFunding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_funding.urls')),
    path('users/',include('app_users.urls')),
]

13-FundProjects_Django/app_funding/urls.py
from django.urls import path
from . import views

app_name = 'app_funding'

urlpatterns = [
    # ex: ''
    path('', views.HomePageView.as_view(), name='home'),
    path('projekt/<int:pk>/', views.DetailProjectView.as_view(), name='detail-project'),
    # ex: '' 
    path('booking/<int:booking_id>/reactivate-request/', views.ReactivateBookingView.as_view() ,name='booking-reactivate-request'),
    path('booking/<int:follower_id>/book-request/', views.RequestBookingView.as_view() ,name='booking-request'),
    # ex: '' 
    path('project/<int:project_pk>/follow/', views.ProjectFollowView.as_view() ,name='follow'),
    # ex: ''
    path('extend-booking/<uuid:token>/', views.ExtendBookingView.as_view(), name='extend-booking'),
]

13-FundProjects_Django/app_users/urls.py
from django.urls import path
from .views import LoginUserView, LogoutUserView

app_name = 'app_users'

urlpatterns = [
    # ex 'users/'
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
]

13-FundProjects_Django/templates/funding/includes/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Fund-Your-Project-Django {{ current_year }}</p></div>
</footer>

13-FundProjects_Django/templates/funding/includes/header.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'app_funding:home' %}">Fund-Your-Project-Django</a>
    </div>
    <div class="d-flex">
        {% if request.user.is_authenticated %}
            <!-- User is logged in -->
            <a href="{% url 'app_users:logout' %}">
                <button class="btn btn-outline-dark">
                    <i class="bi bi-person-circle"></i>
                    LogOut
                </button>
            </a>
            <button class="btn btn-outline-dark">
                <i class="bi bi-person-circle"></i>
                {{ request.user.username }}
            </button>
        {% else %}
            <!-- User is not logged in -->
            <a href="{% url 'app_users:login' %}">
                <button class="btn btn-outline-dark">
                    <i class="bi bi-person-circle"></i>
                    LogIn
                </button>
            </a>
        {% endif %}
    </div>
</nav>