14-My_Library/library_project/app_catalog/urls.py
from django.urls import path  # , include, re_path
from app_catalog import views

app_name = 'app_catalog'

urlpatterns = [
    # ex: catalog/
    path('', views.IndexView.as_view(), name='index'),
    path('book/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    # re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),  # noqa
    path('author/', views.AutorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),  # noqa
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name='borrowed-books'),  # noqa
    path('borrowed/', views.AllBorrowedBooksByUserListView.as_view(), name='borrowed-all'),  # noqa
    path('book/<uuid:pk>/renew/', views.RenewBookLibrarianView.as_view(), name='renew-book-librarian'),  # noqa
    # authors path
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),  # noqa
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),  # noqa
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),  # noqa
    # books path
    path('book/create/', views.BookCreate.as_view(), name='book-create'),  # noqa
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),  # noqa
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),  # noqa
]

14-My_Library/library_project/app_core/urls.py
"""
urls for the health check of the application
"""
from django.urls import path
from . import views

app_name = 'app_core'

urlpatterns = [
    # ex: health/
    path('health-check/', views.health_check, name='health-check'),
]

14-My_Library/library_project/library_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('health/', include('app_core.urls')),
    path('catalog/', include('app_catalog.urls')),
    # redirecting - root url to catalog
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    # adds django site authentication urls
    # accounts/ login/ [name='login']
    # accounts/ logout/ [name='logout']
    # accounts/ password_change/ [name='password_change']
    # accounts/ password_change/done/ [name='password_change_done']
    # accounts/ password_reset/ [name='password_reset']
    # accounts/ password_reset/done/ [name='password_reset_done']
    # accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/ reset/done/ [name='password_reset_complete']
    path('accounts/', include('django.contrib.auth.urls')),
]

# for serving files in development - only!!
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

14-My_Library/library_project/app_catalog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
import uuid


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        _("name"),
        max_length=200,
        help_text=_("Enter a book genre (e.g. Science Fiction)")
    )

    def __str__(self) -> str:
        """String representing the Model object."""
        return self.name

    def __repr__(self) -> str:
        """unambiguous string representation -
        meant for developers and debugging purposes"""
        return (
            f"{self.__class__.__name__} class, "
            f"(id={self.id}, name={self.name})"
        )


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)"""
    title = models.CharField(
        _("title"),
        max_length=200,
    )
    # foreign key, one author -> many books
    author = models.ForeignKey(
        'Author',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("author")
    )
    summary = models.TextField(
        _("summary"),
        max_length=1000,
        help_text=_("Enter a brief description of the book")
    )
    isbn = models.CharField(
        _("ISBN"),
        max_length=13,
        unique=True,
        help_text=_(
            '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'  # noqa
            )
    )
    # Many to Many relations bc genre can cover many books, and many books can
    # have same generes
    genre = models.ManyToManyField(
        Genre,
        help_text=_("Select a genre for this book"),
        verbose_name=_("genre")
    )
    language = models.ForeignKey(
        'Language',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("language"),
    )

    class Meta:
        ordering = ['title']

    def __str__(self) -> str:
        """String representing the Model object"""
        return (
            self.title if not self.author
            else f"{self.title} by {self.author.first_name[0]}.{self.author.last_name}"  # noqa
        )

    def __repr__(self):
        """unambiguous string representation -
        meant for developers and debugging purposes"""
        return (
            f"{self.__class__.__name__} class, "
            f"(id={self.id}, title={self.title} "
            f"author='{self.author}', isbn='{self.isbn})"
        )

    def get_absolute_url(self):  # to see the view on site button
        """Returns the URL to access a detail record for this book."""
        return reverse('app_catalog:book-detail', kwargs={'pk': self.pk})


class BookInstance(models.Model):
    """Model representing a specific copy of a book
    (i.e.) that can be borrowed from the library."""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_("Unique ID for this particular book across whole library")
    )
    # realtionship one book -> many bookInstances
    book = models.ForeignKey(
        'Book',
        on_delete=models.RESTRICT,
        null=True,
        verbose_name=_("book")
    )
    borrower = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("borrower")
    )
    imprint = models.CharField(
        _("imprint"),
        max_length=200
    )
    due_back = models.DateField(
        _("Due back"),
        null=True,
        blank=True,
        help_text=_("Enter the due date for this item")
    )

    LOAN_STATUS = (
        ('m', _('Maintenance')),
        ('o', _('On loan')),
        ('a', _('Available')),
        ('r', _('Reserved')),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default=LOAN_STATUS[0][0],
        help_text=_("Book availability"),
    )

    class Meta:
        ordering = ['due_back']
        permissions = [
            ("can_mark_returned", "Can Set book as returned"),
            ("can_renew", "Can extend the book return date"),
            ("can_view_staff", "Can see the staff view"),
        ]

    def __str__(self) -> str:
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"

    def __repr__(self):
        """unambiguous string representation -
        meant for developers and debugging purposes"""
        return (
            f"{self.__class__.__name__} class, "
            f"(id={self.id}, book={self.book}, "
            f"status={self.get_status_display()}"
            f"due_back={self.due_back}"
        )

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on
        the due date and current date"""
        # print(self.due_back.date(),timezone.now().date())
        return self.due_back and self.due_back < timezone.now().date()


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(
        _("first name"),
        max_length=100
    )
    last_name = models.CharField(
        _("last name"),
        max_length=100
    )
    date_of_birth = models.DateField(
        _("Date of birth"),
        null=True,
        blank=True,
    )
    date_of_death = models.DateField(
        _("Date of death"),
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self) -> str:
        """String for representing the Model object"""
        return f"{self.first_name}, {self.last_name}"

    def __repr__(self):
        """unambiguous string representation -
        meant for developers and debugging purposes"""
        return (
            f"{self.__class__.__name__} class, "
            f"(id={self.id}, first_name={self.first_name},"
            f"last_name={self.last_name}"
            f"date_of_birth='{self.date_of_birth}', date_of_death='{self.date_of_death})" # noqa
        )

    def get_absolute_url(self):  # to see the view on site button
        """Returns the URL to access a particular author instance."""
        return reverse('app_catalog:author-detail', kwargs={'pk': self.pk})

    def clean(self) -> None:
        """checking if the date of birth is before the date of birth"""
        # parent class clean method logic
        super().clean()
        # cusotm logic
        if self.date_of_birth and self.date_of_death:
            if self.date_of_death < self.date_of_birth:
                raise ValidationError("Date of death must be after the date of birth.")  # noqa


class Language(models.Model):
    """Model representing a Language (English, French etc.)."""
    name = models.CharField(
        _("name"),
        max_length=100,
        help_text=_("Enter the language of the book")
    )

    def __str__(self) -> str:
        """String for representing the Model object"""
        return self.name

    def __repr__(self):
        """unambiguous string representation -
        meant for developers and debugging purposes"""
        return (
            f"{self.__class__.__name__} class, "
            f"(id={self.id}, name={self.name},"
        )

14-My_Library/library_project/app_catalog/forms.py
from datetime import date, timedelta
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from app_catalog.models import BookInstance


# class RenewBookForm(forms.Form):
#     """Form for renewing a book"""
#     renewal_date = forms.DateField(
#         help_text=_("Enter a date between now and 4 weeks (default 3).")
#     )

#     def clean_renewal_date(self):
#         """validating the renewal_date field"""
#         data = self.cleaned_data['renewal_date']

#         # check if date is in the future
#         if data < date.today():
#             raise ValidationError(_("Invalid date - renewal in the past"))

#         # check if the date is more than 4 weeks in the future
#         if data > (date.today() + timedelta(weeks=4)):
#             raise ValidationError(_("Invalid date - renewal more than 4 weeks in the future"))  # noqa

#         # returning the cleaned data
#         return data


class RenewBookModelForm(forms.ModelForm):
    """ModelForm for renewing a book"""
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {
            'due_back': _('Enter a date between now and 4 weeks (default 3).')
        }

    def clean_due_back(self):
        """validating the due_back field"""
        data = self.cleaned_data['due_back']

        # check if date is in the future
        if data < date.today():
            raise ValidationError(_("Invalid date - renewal in the past"))

        # check if the date is more than 4 weeks in the future
        if data > (date.today() + timedelta(weeks=4)):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks in the future"))  # noqa

        # returning the cleaned data
        return data

14-My_Library/library_project/app_catalog/templates/app_catalog/author_confirm_delete.html
{% extends 'library/base.html' %}
{% block title %}My Library - Author-delete{% endblock %}
{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{ author }}?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/author_detail.html
{% extends 'library/base.html' %}
{% block title %}My Library - Author-detail{% endblock %}
{% block content %}
    <h1>Author: {{ author }}</h1>
    <p class="text-muted">{{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</p>
    <div class="copies">
        <h4>Books</h4>
        {% for book in author.book_set.all %}
          <a class="book-detail-title" href="{% url 'app_catalog:book-detail' book.pk %}">
            <strong>{{ book.title }}</strong>
          </a>
          <span>({{book.bookinstance_set.all.count}})</span>
          <p class="book-detail-summary">{{ book.summary }}</p>
        {% endfor %}
    </div>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/author_form.html
{% extends 'library/base.html' %}
{% block title %}My Library - Author-form{% endblock %}
{% block content %}
<h1>Adding a new author</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/author_list.html
{% extends 'library/base.html' %}
{% block title %}My Library - Author List{% endblock %}
{% block content %}
    <h1>
        Author list
        {% if perms.app_catalog.add_author and perms.app_catalog.view_author %}
            <a class="btn btn-dark btn-lg" href='{% url "app_catalog:author-create" %}'>Add</a>
        {% endif %}
    </h1>
    <ul>
        {% for author in author_list %}
            <li>
                <a href="{% url 'app_catalog:author-detail' pk=author.pk %}">
                    {{ author }}
                    (
                        {{ author.date_of_birth }} 
                        - 
                        {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}
                    )
                </a>
                {% if perms.app_catalog.change_author and perms.app_catalog.view_author %}
                    <a class="py-0 btn btn-light" href='{% url "app_catalog:author-update" author.pk %}'>Update</a>
                {% endif %}
                {% if perms.app_catalog.delete_author and perms.app_catalog.view_author %}
                    <a class="py-0 btn btn-danger" href='{% url "app_catalog:author-delete" author.pk %}'>X</a>
                {% endif %}
            </li>
        {% empty %}
            <h2>The library does not have any Authors yet.<h2>
            <p>Come back later!<p>
        {% endfor %}
    </ul>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/book_confirm_delete.html
{% extends 'library/base.html' %}
{% block title %}My Library - Book-delete{% endblock %}
{% block content %}
<h1>Delete Book</h1>
<p>Are you sure you want to delete the book: {{ book }}?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/book_detail.html
{% extends 'library/base.html' %}
{% block title %}My Library - Book-detail{% endblock %}
{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong> {% if book.author %}<a href='{% url "app_catalog:author-detail" book.author.pk %}'>{{ book.author }}</a>{% else %}Not defined{% endif %}</p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
    <div class="copies">
        <h4>Copies</h4>
        {% for copy in book.bookinstance_set.all %}
          <hr />
          <p
            class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
          </p>
          {% if copy.status != 'a' %}
            <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
          {% endif %}
          <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
          <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
      </div>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/book_form.html
{% extends 'library/base.html' %}
{% block title %}My Library - Book-form{% endblock %}
{% block content %}
<h1>Creating a new book</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/book_list.html
{% extends 'library/base.html' %}
{% block title %}My Library - Books{% endblock %}
{% block content %}
    <h1>
        Book list
        {% if perms.app_catalog.add_book and perms.app_catalog.view_book %}
            <a class="btn btn-dark btn-lg" href='{% url "app_catalog:book-create" %}'>Add</a>
        {% endif %}
    </h1>
    <ul>
        {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                {% comment %} <a href="{% url 'app_catalog:book-detail' pk=book.pk %}">{{ book.title }}</a> {% endcomment %}
                ({{ book.author }})
                {% if perms.app_catalog.change_book and perms.app_catalog.view_book %}
                    <a class="py-0 btn btn-light" href='{% url "app_catalog:book-update" book.pk %}'>Update</a>
                {% endif %}
                {% if perms.app_catalog.delete_book and perms.app_catalog.view_book %}
                    <a class="py-0 btn btn-danger" href='{% url "app_catalog:book-delete" book.pk %}'>X</a>
                {% endif %}
            </li>
        {% empty %}
            <h2>The library does not have any books yet.<h2>
            <p>Come back later!<p>
        {% endfor %}
    </ul>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/book_renew_librarian.html
{% extends 'library/base.html' %}
{% block title %}My Library - Extend book back date{% endblock %}
{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p {% if book_instance.is_overdue %}class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/bookinstance_list_borrowed.html
{% extends 'library/base.html' %}
{% block title %}My Library - All Borrowed Books{% endblock %}
{% block content %}
    <h1>All Borrowed books</h1>
    <ul>
        {% for bookinstance in object_list %}
            <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'app_catalog:book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a>
                (Due: {{ bookinstance.due_back }}) - {{ bookinstance.borrower.get_username }}
                {% if perms.app_catalog.can_renew %}
                    <a href='{% url "app_catalog:renew-book-librarian" bookinstance.id %}'>Renew</a>
                {% endif %}
            </li>
        {% empty %}
            <h2>No one borrowed books yet.<h2>
        {% endfor %}
    </ul>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/bookinstance_list_borrowed_user.html
{% extends 'library/base.html' %}
{% block title %}My Library - My Books{% endblock %}
{% block content %}
    <h1>Borrowed books</h1>
    <ul>
        {% for bookinstance in object_list %}
            <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'app_catalog:book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a>
                (Due: {{ bookinstance.due_back }})
            </li>
        {% empty %}
            <h2>You dont have any books yet.<h2>
            <p>Brows the library to find your next adventure!<p>
        {% endfor %}
    </ul>
{% endblock  %}

14-My_Library/library_project/app_catalog/templates/app_catalog/index.html
{% extends 'library/base.html' %}
{% block title %}My Library - Home{% endblock %}
{% block content %}
    <h1>My Library - Home</h1>
    <p>
        Welcome to My Library,
    </p>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instaces_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Genres:</strong> {{ num_genres }}</li>
    </ul>
    <p>
        You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>
{% endblock  %}