12-User_Management_SQLAlchemy_Django/app_add_models/urls.py
from django.urls import path
from . import views

app_name = 'app_add_models'

urlpatterns = [
    path('users/', views.UserListView.as_view(), name='home'),
    path('add/', views.AddCreateView.as_view(), name='add'),
    path('delete/<int:pk>/', views.DeleteUserView.as_view(), name='delete_user'),
]

12-User_Management_SQLAlchemy_Django/sqlalchemy_test/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('app_add_models.urls')),   
    # path('admin/', admin.site.urls), 
]

12-User_Management_SQLAlchemy_Django/app_add_models/models.py
from django.db import models
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
# from sqlalchemy_test.settings import db_session, DATABASES
from sqlalchemy_test.settings import SA_DB_SESSION
from django.conf import settings
from sqlalchemy import inspect

# Create your models here.
Base = declarative_base()

class UserModel(Base):
    __tablename__ = 'my_users_table'

    id = Column(Integer, primary_key=True)
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    email = Column(String(100), nullable=False, unique=True)
    description = Column(String(200))
     
    def __str__(self): 
        return f"{self.email}"
    
    @classmethod
    def get_all(cls):
        all_data = None
        with SA_DB_SESSION() as db_session: 
            all_data = db_session.query(cls).all()
        return all_data


#creating the given table if it dosent exists
def create_users_table(engine):
    inspector = inspect(engine)
    if not inspector.has_table(UserModel.__tablename__):
        Base.metadata.create_all(engine)
        
create_users_table(settings.DATABASES['default']['SA_ENGINE'])


# In Django's class-based views, the model attribute expects a Django Model class, 
# which has an _meta attribute and more. Therefore, you cannot use SQLAlchemy models directly with Django's class-based views.
# One way to work around this is to create a simple Django model that mirrors the columns 
# of your SQLAlchemy model, and then use that model in your class-based views. 
# Alternatively, you can write your own custom view that do not rely on Django's class-based views,
class DjangoUserModel(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)

12-User_Management_SQLAlchemy_Django/app_add_models/forms.py
from app_add_models.models import UserModel
from django.core.exceptions import ValidationError
from django import forms
from sqlalchemy_test.settings import SA_DB_SESSION

    

class UserForm(forms.Form):
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    email = forms.EmailField(
        max_length=100, 
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'maxlength': 200, 'class': 'form-control', 'rows':"3"}), 
        required=False
    )
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        with SA_DB_SESSION() as db_session:
            if db_session.query(UserModel).filter_by(email=email).first():
                raise ValidationError('This email address is already in use.')
        return email
    

12-User_Management_SQLAlchemy_Django/app_add_models/views.py
from typing import Any, Dict, Optional, Type
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views.generic import ListView, FormView
from django.views.generic.base import View 
from app_add_models.models import UserModel, DjangoUserModel
from django.urls import reverse_lazy
import datetime
from sqlalchemy_test.settings import SA_DB_SESSION
from app_add_models.forms import UserForm
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
 

# Create your views here.
class UserListView(ListView):
    model = UserModel
    template_name = 'app_add_models/index.html'
    context_object_name = 'all_users'
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['current_year']= datetime.datetime.now().year
        return context
    
    def get_queryset(self):        
        return UserModel.get_all()
    
class AddCreateView(FormView):
    model = DjangoUserModel
    template_name = 'app_add_models/add.html'
    form_class = UserForm
    # fields = ['first_name', 'last_name', 'email', 'description']
    success_url = reverse_lazy('app_add_models:home')
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['current_year']= datetime.datetime.now().year
        return context
    
    # saving new user to the database if data is valid
    def form_valid(self, form) -> HttpResponse:
        new_user = UserModel(
            first_name = form.cleaned_data['first_name'],
            last_name = form.cleaned_data['last_name'],
            email = form.cleaned_data['email'],
            description = form.cleaned_data['description'],
        )
        # new_user = form.save(commit=False)
        with SA_DB_SESSION() as db_session:
            db_session.add(new_user)
            db_session.commit()
        
        return HttpResponseRedirect(self.get_success_url())
        # preventing from saving the django model
        # return super().form_valid(form)
    
class DeleteUserView(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk',None)
        
        if not pk:
            return HttpResponseBadRequest()
        
        with SA_DB_SESSION() as db_session:
            # querry the user with the given id
            user = db_session.get(UserModel, pk)
            
            if not user:
                return HttpResponseBadRequest()
            
            # TODO: error handling exception handling is missing - to add
            # if somehing happens witht he databse expetion need to be handled !
            db_session.delete(user)
            db_session.commit()
        
        # return HttpResponse(status=204)
        return HttpResponseRedirect(reverse('app_add_models:home'))

12-User_Management_SQLAlchemy_Django/app_add_models/templates/app_add_models/add.html
{% extends 'app_add_models/base.html' %}

{% block content %}
    <div class="container text-center mt-5">
        <h1>Add a new user</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" class="btn btn-dark">Add user</button>
        </form>
    </div>
{% endblock %}

12-User_Management_SQLAlchemy_Django/app_add_models/templates/app_add_models/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQLALCHEMY TEST</title>
    {% block csstAdded %}   
        <!-- bootstrap 5.3 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
    <!--Header content-->
    {% include 'app_add_models/includes/header.html' %}

    <main>{% block content %} {% endblock %}</main>

    <!--Footer content-->
    {% include 'app_add_models/includes/footer.html' %}
    
    {% block javaScriptAdded %} 
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

12-User_Management_SQLAlchemy_Django/app_add_models/templates/app_add_models/includes/footer.html
<footer class="fixed-bottom">
  <article>
    <p class="text-center fw-light">Copyright SQLAlchemy test {{ current_year }}</p>
  </article>
</footer>

12-User_Management_SQLAlchemy_Django/app_add_models/templates/app_add_models/includes/header.html
<header>
    <nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'app_add_models:home' %}">SQLALCHEMY</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#myNavBar" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="myNavBar">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app_add_models:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_add_models:add' %}">ADD</a>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

12-User_Management_SQLAlchemy_Django/app_add_models/templates/app_add_models/index.html
{% extends 'app_add_models/base.html' %}

{% block content %}
<table class="table container-md">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
        {% for user in all_users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ user.email }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>
                    <form action="{% url 'app_add_models:delete_user' pk=user.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="link-danger link-underline-opacity-0">X</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td>Add users first!</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}